FROM python:3.13.2-alpine3.21

WORKDIR '/app'

RUN apk add --no-cache linux-headers g++

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . . 

RUN addgroup -S uwsgi && adduser -S uwsgi -G uwsgi

USER uwsgi

CMD ["uwsgi", "--ini", "app.ini"]